name: Build/release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 14

      - name: Install dependencies
        run: sudo apt install flatpak flatpak-builder

      - name: Install dependencies
        run: npm ci

      - name: package webpack scripts
        run: npm run package

      - name: build flatpak
        run: npm run build-flatpak-debug

      - name: upload flatpak
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: dist
